version: '3.7'

services:
  db:
    container_name: db
    build:
      context: ./db
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  api:
    container_name: api
    build:
      context: ./api
    environment:
      FRONTEND_URL: http://localhost
      JWT_SECRET_KEY: A_VERY_SECURE_SECRET_KEY
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SSLMODE: 'false'
    ports:
      - 3000:3000
    volumes:
      - ./api/src:/api/src
    depends_on:
      - db
  app:
    container_name: app
    build:
      context: ./app
    ports:
      - 80:80
    volumes:
      - ./app/src:/app
